
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app2
  labels:
    app: demo-app2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app2
  template:
    metadata:
      labels:
        app: demo-app2
    spec:
      containers:
        - name: demo-app2
          image: docker.io/ankitsonari376/demo-app2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
