
apiVersion: v1
kind: Service
metadata:
  name: demo-appxyz
  labels:
    app: demo-appxyz
spec:
  type: NodePort
  ports:
    - port: 8080        # Service port
      targetPort: 8080  # Container port
      protocol: TCP
      name: http
      nodePort: 31000   # Optional: specify NodePort (must be between 30000â€“32767)
  selector:
    app: demo-appxyz
